export type BuildingEntry = {
  name: string;
  code: string;
  description: string;
  accessibility: string;
  image: string;
};

export const TMU_BUILDINGS: BuildingEntry[] = [
  {
    name: "10 King Street East",
    code: "MAG",
    description: "10 King Street East is a Toronto Metropolitan University facility located in the downtown core.",
    accessibility: "Accessibility information will be updated soon.",
    image: "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "101 Gerrard Street East",
    code: "COP",
    description: "101 Gerrard Street East is a downtown campus building used for academic programs.",
    accessibility: "Accessibility information will be updated soon.",
    image: "https://images.unsplash.com/photo-1523413651479-597eb2da0ad6?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "111 Bond Street",
    code: "BON",
    description: "111 Bond Street supports Toronto Metropolitan University student and academic life.",
    accessibility: "Accessibility information will be updated soon.",
    image: "https://images.unsplash.com/photo-1501183638710-841dd1904471?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "112 Bond Street",
    code: "BND",
    description: "112 Bond Street hosts classroom and administrative space.",
    accessibility: "Accessibility information will be updated soon.",
    image: "https://images.unsplash.com/photo-1501183638710-841dd1904471?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "114 Bond Street",
    code: "PRO",
    description: "114 Bond Street is part of TMU's downtown campus footprint.",
    accessibility: "Accessibility information will be updated soon.",
    image: "https://images.unsplash.com/photo-1451976426598-a7593bd6d0b2?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "147 Dalhousie Street",
    code: "DAL",
    description: "147 Dalhousie Street provides academic and support services in the city center.",
    accessibility: "Accessibility information will be updated soon.",
    image: "https://images.unsplash.com/photo-1430285561322-7808604715df?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "401 Richmond Street West",
    code: "RCD",
    description: "401 Richmond Street West is a TMU location west of the main campus.",
    accessibility: "Accessibility information will be updated soon.",
    image: "https://images.unsplash.com/photo-1430285561322-7808604715df?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "415 Yonge Street",
    code: "YNG",
    description: "415 Yonge Street is used for classes and services near the main campus.",
    accessibility: "Accessibility information will be updated soon.",
    image: "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "Architecture Building",
    code: "ARC",
    description: "The Architecture Building hosts studios, labs, and classrooms for design programs.",
    accessibility: "Accessibility information will be updated soon.",
    image: "https://images.unsplash.com/photo-1465808024277-5cb1918a4665?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "Atrium on Bay",
    code: "AOB",
    description: "Atrium on Bay is a multi-use TMU facility with academic and office space.",
    accessibility: "Accessibility information will be updated soon.",
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "Bell Trinity Square",
    code: "BTS",
    description: "Bell Trinity Square supports downtown academic programming.",
    accessibility: "Accessibility information will be updated soon.",
    image: "https://images.unsplash.com/photo-1505843513577-22bb7d21e455?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "Brampton City Hall",
    code: "BRU",
    description: "Brampton City Hall hosts TMU offerings in the Brampton area.",
    accessibility: "Accessibility information will be updated soon.",
    image: "https://images.unsplash.com/photo-1464146072230-91cabc968266?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "Campus Store",
    code: "BKS",
    description: "The Campus Store provides course materials and TMU apparel.",
    accessibility: "Accessibility information will be updated soon.",
    image: "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "Carlton Cinema",
    code: "CAR",
    description: "Carlton Cinema is a partner venue used for TMU events.",
    accessibility: "Accessibility information will be updated soon.",
    image: "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "Centre for Urban Innovation",
    code: "CUI",
    description: "Centre for Urban Innovation houses research and innovation initiatives.",
    accessibility: "Accessibility information will be updated soon.",
    image: "https://images.unsplash.com/photo-1451976426598-a7593bd6d0b2?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "Civil Engineering Building – Monetary Times",
    code: "MON",
    description: "The Civil Engineering Building supports engineering programs and labs.",
    accessibility: "Accessibility information will be updated soon.",
    image: "https://images.unsplash.com/photo-1465808024277-5cb1918a4665?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "Creative Innovation Studio",
    code: "CIS",
    description: "Creative Innovation Studio is a makerspace and collaboration hub.",
    accessibility: "Accessibility information will be updated soon.",
    image: "https://images.unsplash.com/photo-1465808024277-5cb1918a4665?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "Daphne Cockwell Health Sciences Complex",
    code: "DCC",
    description: "DCC is a flagship health sciences and community building.",
    accessibility: "Accessibility information will be updated soon.",
    image: "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "Downsview",
    code: "DWV",
    description: "Downsview is a satellite TMU location for specialized programs.",
    accessibility: "Accessibility information will be updated soon.",
    image: "https://images.unsplash.com/photo-1501183638710-841dd1904471?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "English Language Institute and International College – College Park",
    code: "CPK",
    description: "College Park hosts ELI and international student programs.",
    accessibility: "Accessibility information will be updated soon.",
    image: "https://images.unsplash.com/photo-1523413651479-597eb2da0ad6?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "Engineering Building",
    code: "ENG",
    description:
      "ENG is on the east side of Church St. and spans almost the full length of the block from Gould St. to just north of Dundas St. The building provides facilities for Computer Science, Mathematics, Aerospace Engineering, Civil Engineering and Electrical, Computer and Biomedical Engineering. It also has the administrative offices for the Faculty of Engineering and Architectural Science.",
    accessibility:
      "Both the main and north entrances have barrier-free approaches (the north entrance has a ramp along the building face) and automatic door operators. There are single-occupancy washrooms on most floors, except the Lower Ground floor, which has washrooms with stalls that have accessibility features. The elevator lobby is in the centre section of the building opposite the Church St. main entrance.",
    image: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "Heidelberg Centre",
    code: "HEI",
    description: "Heidelberg Centre is a university research and teaching site abroad.",
    accessibility: "Accessibility information will be updated soon.",
    image: "https://images.unsplash.com/photo-1501183638710-841dd1904471?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "Heidelberg Institute for International Research",
    code: "HIR",
    description: "HIR provides international research collaborations for TMU.",
    accessibility: "Accessibility information will be updated soon.",
    image: "https://images.unsplash.com/photo-1501183638710-841dd1904471?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "Image Arts Building",
    code: "IMA",
    description: "Image Arts Building supports media, photography, and film programs.",
    accessibility: "Accessibility information will be updated soon.",
    image: "https://images.unsplash.com/photo-1505843513577-22bb7d21e455?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "International Living/Learning Centre",
    code: "ILC",
    description: "ILC provides residential and student services.",
    accessibility: "Accessibility information will be updated soon.",
    image: "https://images.unsplash.com/photo-1501183638710-841dd1904471?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "Jorgenson Hall",
    code: "JOR",
    description: "Jorgenson Hall contains classrooms and student services.",
    accessibility: "Accessibility information will be updated soon.",
    image: "https://images.unsplash.com/photo-1465808024277-5cb1918a4665?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "Kerr Hall East",
    code: "KHE",
    description: "Kerr Hall East is part of the TMU Kerr Hall complex.",
    accessibility: "Accessibility information will be updated soon.",
    image: "https://images.unsplash.com/photo-1465808024277-5cb1918a4665?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "Kerr Hall North",
    code: "KHN",
    description: "Kerr Hall North houses classrooms and labs.",
    accessibility: "Accessibility information will be updated soon.",
    image: "https://images.unsplash.com/photo-1465808024277-5cb1918a4665?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "Kerr Hall South",
    code: "KHS",
    description: "Kerr Hall South supports academic and administrative spaces.",
    accessibility: "Accessibility information will be updated soon.",
    image: "https://images.unsplash.com/photo-1465808024277-5cb1918a4665?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "Kerr Hall West",
    code: "KHW",
    description: "Kerr Hall West is part of the central campus complex.",
    accessibility: "Accessibility information will be updated soon.",
    image: "https://images.unsplash.com/photo-1465808024277-5cb1918a4665?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "Kerr Hall Quad",
    code: "KHQ",
    description: "Kerr Hall Quad is the interior courtyard of Kerr Hall.",
    accessibility: "Accessibility information will be updated soon.",
    image: "https://images.unsplash.com/photo-1465808024277-5cb1918a4665?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "Library",
    code: "LIB",
    description: "The Library provides study spaces, collections, and academic support.",
    accessibility: "Accessibility information will be updated soon.",
    image: "https://images.unsplash.com/photo-1507842217343-583bb7270b66?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "Mattamy Athletic Centre",
    code: "MAC",
    description: "Mattamy Athletic Centre is TMU's athletic and recreation facility.",
    accessibility: "Accessibility information will be updated soon.",
    image: "https://images.unsplash.com/photo-1521537634581-0dced2fee2ef?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "Merchandise Building",
    code: "MER",
    description: "Merchandise Building hosts classrooms and labs.",
    accessibility: "Accessibility information will be updated soon.",
    image: "https://images.unsplash.com/photo-1451976426598-a7593bd6d0b2?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "O'Keefe House",
    code: "OKE",
    description: "O'Keefe House is a heritage building used for academic programs.",
    accessibility: "Accessibility information will be updated soon.",
    image: "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "Oakham House",
    code: "OAK",
    description: "Oakham House hosts meetings, events, and student spaces.",
    accessibility: "Accessibility information will be updated soon.",
    image: "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "Parking Garage",
    code: "PKG",
    description: "The TMU parking garage serves commuter parking.",
    accessibility: "Accessibility information will be updated soon.",
    image: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "Podium",
    code: "POD",
    description: "The Podium contains classrooms, labs, and student services.",
    accessibility: "Accessibility information will be updated soon.",
    image: "https://images.unsplash.com/photo-1501183638710-841dd1904471?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "Research and Graduate Studies",
    code: "RGS",
    description: "RGS supports research and graduate studies.",
    accessibility: "Accessibility information will be updated soon.",
    image: "https://images.unsplash.com/photo-1501183638710-841dd1904471?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "Rogers Communication Centre",
    code: "RCC",
    description: "RCC hosts communications and media programs.",
    accessibility: "Accessibility information will be updated soon.",
    image: "https://images.unsplash.com/photo-1465808024277-5cb1918a4665?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "Ryerson Student Centre",
    code: "SCC",
    description: "The Student Campus Centre is a hub for student life and services.",
    accessibility: "Accessibility information will be updated soon.",
    image: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "School of Image Arts",
    code: "SIA",
    description: "SIA supports creative and visual arts programming.",
    accessibility: "Accessibility information will be updated soon.",
    image: "https://images.unsplash.com/photo-1505843513577-22bb7d21e455?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "Student Learning Centre",
    code: "SLC",
    description: "Student Learning Centre provides study spaces and services.",
    accessibility: "Accessibility information will be updated soon.",
    image: "https://images.unsplash.com/photo-1507842217343-583bb7270b66?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "Ted Rogers School of Management",
    code: "TRS",
    description: "TRS is home to the Ted Rogers School of Management.",
    accessibility: "Accessibility information will be updated soon.",
    image: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "Toronto Metropolitan University Library",
    code: "LIB",
    description: "The TMU Library supports research, studying, and learning resources.",
    accessibility: "Accessibility information will be updated soon.",
    image: "https://images.unsplash.com/photo-1507842217343-583bb7270b66?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "Victoria Building",
    code: "VIC",
    description: "Victoria Building provides academic and administrative space.",
    accessibility: "Accessibility information will be updated soon.",
    image: "https://images.unsplash.com/photo-1501183638710-841dd1904471?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "Victoria Parking Garage",
    code: "VPG",
    description: "Victoria Parking Garage supports commuter parking options.",
    accessibility: "Accessibility information will be updated soon.",
    image: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "Yonge-Dundas Square",
    code: "YDS",
    description: "Yonge-Dundas Square is a nearby landmark used for events.",
    accessibility: "Accessibility information will be updated soon.",
    image: "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=800&q=80",
  },
];

export const ENG_ROOMS = Array.from({ length: 40 }, (_, index) => {
  const floor = Math.floor(index / 10) + 1;
  const roomOffset = (index % 10) + 1;
  const roomNumber = `${floor}${roomOffset.toString().padStart(2, "0")}`;
  return `ENG ${roomNumber}`;
});
